### ISSUE TITLE
updateManager: Use async.eachLimit to uncompress multiple files at once

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#13]
We need to disable `{ lazyEntries: true }` and then limit to a reasonable number (???) of files at once so that we don't reach the OS's max file limit.

**Comment by bilou84** [comment]
Anatagawa got problems to download the game system but it worked fine with the love2d and the web systems. For game, it got stucked at 97%, during the unzipp then.
There was no errors or anything. I suspect it may have something to do with that?

**Comment by bilou84** [comment]
So I was thinking that currently we were doing the reading in parallel with no limit and that we wanted to add a limit. Actually we are doing the reading one by one and you were suggesting doing multiple files at once instead to go faster right?
The lib author doesn't recommend it. See https://github.com/thejoshwolfe/yauzl/issues/22.

Either way, it is probably not related to the bug Anata hit so...

**Comment by elisee** [comment]
Updates are working fine now so I think we can forget about this.
