### ISSUE TITLE
When launching games: "Failed to initialize renderer. Your device might not support WebGL."

### ISSUE THREAD

**Issue by mk-pmb** [superpowers/superpowers-app#19]
Some days ago I thought this was specific to the `discover-superpowers-game` and [reported it there](https://github.com/superpowers-extra/discover-superpowers-game/issues/4), but now that I managed to build the development version of Superpowers, I think it's more of an app issue.

**Problem:** When launching a game from the game editor, the loading screen leads to "Failed to initialize renderer. Your device might not support WebGL."

**Steps to reproduce:**
- [Install superpowers in devel-mode.](http://docs.superpowers-html5.com/en/development/building-superpowers)
- Install some demo games. Intermediate result:

``` text
Devel environment: Node.js v5.7.1, npm v3.6.0, Ubuntu 12.04.5 LTS precise
sp-dev/app = superpowers/superpowers-app @ d0af9ed: Make travis notify gitter
sp-dev/core = superpowers/superpowers-core @ 2f266e9: SupClient: Store client ID on ProjectClient
sp-dev/core/systems/game = superpowers/superpowers-game @ d1ce643: scene: Allow dropping scene in a prefab again. Fixes #79
sp-dev/proj/discover-superpowers-game = superpowers-extra/discover-superpowers-game @ d388ba3: Create LICENSE.txt
sp-dev/proj/pac-man-like-game = superpowers-extra/pac-man-like-game @ 89c10e0: Create README.md
sp-dev/proj/snow-world-game = superpowers-extra/snow-world-game @ fb9bef0: Create LICENSE.txt
sp-dev/systems/superpowers-love2d = superpowers/superpowers-love2d @ 2867741: README: Add build status badge
```
- Launch the IDE.
- In the servers list sidebar, double-click localhost. (A games list should appear.)
- In the games list, double-click any game. (The game editor should open.)
  - As you might have guessed from the directory list, I tested `discover-superpowers-game`, `pac-man-like-game` and `snow-world-game`.
- In the game editor's top-left dark pane, click the play button. ([Screenshot](http://temp.svenvanbolt.de/discover-fail.bc338d96.jpeg))
- The loading screen appears, then the error message.

**Additional info:**
- Identify browser: In the error screen, press F12 to summon the ECMAScript console. Enter `navigator.userAgent`.
  - My IDE's browser: `"Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) superpowers-app/0.0.0-dev Chrome/47.0.2526.110 Electron/0.36.10 Safari/537.36"`
  - The `Electron/0.36.10` part seems to indicate that the install instructions have lead to an incompatible version of electron.

**Comment by elisee** [comment]
Your installation of Superpowers looks fine and I don't think this is app-related. I replied in more details at your original issues (https://github.com/superpowers-extra/discover-superpowers-game/issues/4), so closing this one.
