### ISSUE TITLE
Catch Ctrl+C and make sure server is stopped properly

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#28]
Just like in the server itself: https://github.com/superpowers/superpowers-core/blob/39cd9e57aa882ab651a7600e328dcf772ff0aed2/server/commands/start.ts#L100

**Comment by elisee** [comment]
Gave it a shot [in a branch](https://github.com/superpowers/superpowers-app/tree/sigint), but it does not seem to work well. It only works some of the time, sometimes the log message is cut off in the middle.

I assume this is an Electron bug of some sort, as of v0.37.5.

**Comment by elisee** [comment]
Confirmed a bug, reported it as https://github.com/electron/electron/issues/5273 and committed commented-out code in c6c704ef1dd7d4ecf7690dbfba3e11d6d34891b9.

**Comment by bilou84** [comment]
Latest news on the issue is that the bug can't (and so won't) be fixed. What should we do on our end?

**Comment by elisee** [comment]
I guess we can't do much. Basically: don't use Ctrl+C when running the app from the command line if you don't want to stopping the server brutally.

Closing as "won't fix", feel free to reopen if new development in Electron happens.
