### ISSUE TITLE
Put window management buttons on the left in OS X

### ISSUE THREAD

**Issue by hatzka-nezumi** [superpowers/superpowers-app#32]
"Window management buttons"? I don't know what they're called. On OS X they're colored circles and go on the left side of the window. For example, in iTunes:

![iTunes](https://cloud.githubusercontent.com/assets/13078933/14869224/42d84dfa-0c8f-11e6-932b-ef190b324ea5.png)

They have the same effects in reversed order (stop, minimize, maximize), and they're already working fine, it's just annoying to have Superpowers work differently from most other applications.

**Comment by elisee** [comment]
Hi! Thanks for the report.

You're using Superpowers v0.19 in which we had custom window decorations. The new app will use the native ones so that will be fixed once it is released.
