### ISSUE TITLE
Windows: Notify that the app is still running when closing all windows

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#37]
We should use Tray.displayBalloon to let people know the app runs in the background. Also we should autoclose the app if no server is running maybe?

**Comment by bilou84** [comment]
Yeah I agree we should close the app when all windows are closed and there is no server running.

**Comment by elisee** [comment]
Might actually not be a good idea because of chat. So maybe just adapt the message to say "Superpowers is running in the background since you're connected to the community chat and/or your local server is still running." (dynamically updated based on what's true).

**Comment by bilou84** [comment]
Well then maybe we should automatically close when local server is off and chat is off. Otherwise, display a notification saying what is keeping Superpowers active.

**Comment by elisee** [comment]
I implemented a simple version that just displays a notification balloon when closing the main window. We don't keep track of other windows for now but I thought at least having that would be useful.
