### ISSUE TITLE
Linux Version - Example Game Not Running

### ISSUE THREAD

**Issue by Occult-Dev** [superpowers/superpowers-app#39]
Hello, I've recently downloaded the v1 builds you made available and have encountered an issue with the Linux x64 one. My OS is Linux Mint Cinnamon (ROSA).

I downloaded the zip, extracted it, and ran the app. First, I'm unable to connect to the server due to an API mismatch, but after changing the API version in the json file, the server connects without issue.

However, when I set up the example platformer project and go to run it, I'm greeted with a blank screen.
The game itself does not run, I see no Superpowers Logo, nor do I get any compiling messages.

I'm currently using the source to run in a browser, which works fine, but the standalone app doesn't seem to want to run the game.

Sorry if this is on my end and not an actual issue (unsure if changing the API version might have caused this), but thought I should let you know.

**Comment by Occult-Dev** [comment]
Hmm.. odd. Tried to install the package again and it worked just fine. Must've gotten fixed, or I was just being dumb.
Either way, this appears to not be an issue anymore as far as I'm aware.

**Comment by elisee** [comment]
Hi!

Changing the API version amounts to working around a compatibility check, so that wouldn't fix anything. You were probably running an older version of the server with the newer app, for some reason. Not sure why but glad you got it fixed.

**Comment by Occult-Dev** [comment]
yea, I think I had the server left over from a previous install maybe? I'm fairly new to Linux and didn't know about the `.local` folder so I didn't remove the Superpowers files from it before getting the new app. Could have been the problem. Thanks! :)
