### ISSUE TITLE
Dismissing the Welcome dialog should not skip core installation

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#43]
See https://itch.io/t/33087/downloaded-v11-on-my-mac-could-not-start-the-server and https://github.com/superpowers/superpowers-app/blob/master/src/renderer/WelcomeDialog.ts.

**Comment by bilou84** [comment]
Oups, yeah I didn't test this situation. I will look into it.

**Comment by elisee** [comment]
It also skipped installing the core, not just the game system, but I guess this fixes both. Also just in case, did you test by pressing Escape to dismiss the dialog? (EDIT: actually maybe there's no other way to dismiss the dialog so you probably did xD)

**Comment by bilou84** [comment]
The core? I don't think so, the core is installed before this dialog.

**Comment by elisee** [comment]
Oh right. Hmm. But that's not consistent with what https://itch.io/t/33087/downloaded-v11-on-my-mac-could-not-start-the-server says. Weird.

**Comment by bilou84** [comment]
Hmm yeah I don't know.
