### ISSUE TITLE
No transparency in Tile Set views but ok in Tile Map

### ISSUE THREAD

**Issue by Ilphrin** [superpowers/superpowers-app#44]
Tried this on Superpowers v1.0 and v1.1 under Linux 64 Bit (Antergos 16.6)
When watching a Tile Set with some pixel having transparency (look around the planets in the screenshots), they have a full opacity when editing/viewing the TileSet, but not when using it in a TileMap or in a Scene.

![screenshot_20160807_155846](https://cloud.githubusercontent.com/assets/7887258/17462817/dbac4620-5cb8-11e6-8ebc-6014124f9d4e.png)
![screenshot_20160807_160310](https://cloud.githubusercontent.com/assets/7887258/17462820/e5f67182-5cb8-11e6-816a-dbd242ff1136.jpg)

(by the way thanks for your awesome software!)

**Comment by bilou84** [comment]
Thanks for the report!
For future reference, this bug is specific to the game system so the issue should have been reported here https://github.com/superpowers/superpowers-game/issues.

**Comment by Ilphrin** [comment]
My bad, I wasn't really sure of where to put this, I suppose I should have written this by default in the core x)
Thanks for the patch! =D
