### ISSUE TITLE
Failed to initialize renderer. Your device might not support WebGL.

### ISSUE THREAD

**Issue by CptDriad** [superpowers/superpowers-app#48]
Not sure if this is the right part of superpowers to say this but I have no clue what this error is.  It's not documented on the manual and it's only been put here without a very coherent reason how it got fixed.

For context, I tested on win32x and win64x of this app. I have the correct update of chrome (if that matters), and yes WebGL does run on my chrome, I checked. My computer is running on 64bit windows.

How do I fix this? Do I need to update something specific? Is it my drivers?

**Comment by elisee** [comment]
Hi!

Thanks for the report. This error means that the app somehow failed to initialize a WebGL context for rendering 2D/3D graphics. Generally that's because your GPU has been blacklisted by Chrome / Electron (for stability reasons) or when your drivers are too old. It is also possible that simply rebooting will fix the issue.

Not something Superpowers can do anything about, it's all in the underlying platform.

Hope that helps! Feel free to reopen if needed.

**Comment by CptDriad** [comment]
I will reopen just incase anyone else needs to view it, also because Im not sure what to do here.

I got an AMD Radeon R9 200 , with the software just updated (16.9.1). Chrome hasnt blacklisted it, because as I've mentioned I already can run WebGL in Chrome and im pretty sure its not an old GPU. Also rebooted twice to make sure.

Is there something I'm doing wrong? I've done everything kinda humanely possible. Is Electron the only reason that remains? Is there any fix for the blacklist? I dont want to purchase a new GPU just to use this product, yknow? If there's other fixes for Electron mucking me over that'd be neat. Especially since this GPU is just fine.

**Comment by elisee** [comment]
Try running the Superpowers app, make sure your server starts and then access your server through http://127.0.0.1:4237/ in Chrome. Does it work? Or do you get the same WebGL error?

**Comment by CptDriad** [comment]
I do not get the WebGL error, and I managed to run the test game through Chrome. Woo!

Whatever the problem is, it's gotta be with Electron, right?

**Comment by elisee** [comment]
Yup, somehow Electron handles WebGL differently than Chrome on your system. Is it possible you have disabled the GPU blacklist in Chrome a long time ago but forgot about doing it?

**Comment by CptDriad** [comment]
Considering how I dont know how to do that, I don't think its possible I did that. How do you do that even?

**Comment by elisee** [comment]
It's in the special chrome://flags config page.

**Comment by CptDriad** [comment]
Should I have Override software rendering list on enabled? If so I believe it is disabled.

**Comment by elisee** [comment]
Yeah. Ok, then I don't know why Electron and Chrome don't give you the same result with WebGL contexts, it's weird.

**Comment by CptDriad** [comment]
Yeah, it definitely must be on Electrons side, and I got no clue how to mess with that.

I guess this is solved? Just use this on Chromes browser side? Because I cant figure out any other fixes.

**Comment by tvortsa** [comment]
Ubuntu 18 laptop Lenovo g505 same trouble with webgl (
How i can setup chrome what use inside superpowers?
