### ISSUE TITLE
Prevent trying to install a plugin if system isn't installed

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-app#50]
Or at least display a proper error message. Right now it looks like it just display `null%` as the progress indicator and then fails.

**Comment by bilou84** [comment]
When the system is not installed, the install button for the plugin should be disabled. Looks like it is for me? Maybe there is an other bug?

**Comment by elisee** [comment]
Hmm, that's weird. The buttons are indeed disabled. I know I had an issue but not sure what it was then...
