### ISSUE TITLE
"Line Message Script"

### ISSUE THREAD

**Issue by GaetanRole** [superpowers/superpowers-app#56]
Hi,

I have a weird problem where the script editor is sometimes empty (showing only "Line Message Script"). Here is a recording of this happening.

![bug](http://i.imgur.com/gikR9tD.gif)

Tested with the master branch and v3.0.0 tag.

Any idea what's happening and how to fix it? I'm not sure if this is a -app or -core or -game issue (or a misconfiguration), so sorry if this is the wrong repo.

**Comment by bilou84** [comment]
Hello! Thanks for the report.

I suspect an issue with Chrome/Electron. Which version of electron are you using?

**Comment by GaetanRole** [comment]
Hi,

I'am using the 1.4.2 version. Indeed, the last electron version is 1.4.3 since one week.

Thanks,

**Comment by bilou84** [comment]
@GaetanRole so you don't have the problem anymore with version 1.4.3?

**Comment by elisee** [comment]
Pretty sure that was the Chrome 53 flex box rendering bug, it also happened in the browser. Fixed now so closing.
